### ISSUE TITLE
Test throws error

### ISSUE THREAD

**Issue by ariymarkowitz** [three-types/three-ts-types#337]
When I run `yarn test` (without having made any changes to the code), I get the following:
```
The 'whitespace' rule threw an error in '/Users/arimarkowitz/three-ts-types/types/three/src/Three.d.ts':
TypeError: Cannot read properties of undefined (reading 'forEach')
    at cb (/Users/arimarkowitz/three-ts-types/node_modules/tslint/lib/rules/whitespaceRule.js:140:45)
    at visitNodes (/Users/arimarkowitz/three-ts-types/node_modules/typescript/lib/typescript.js:31214:30)
    at forEachChildInSourceFile (/Users/arimarkowitz/three-ts-types/node_modules/typescript/lib/typescript.js:31573:20)
    at Object.forEachChild (/Users/arimarkowitz/three-ts-types/node_modules/typescript/lib/typescript.js:31988:47)
    at walk (/Users/arimarkowitz/three-ts-types/node_modules/tslint/lib/rules/whitespaceRule.js:99:8)
    at Rule.AbstractRule.applyWithFunction (/Users/arimarkowitz/three-ts-types/node_modules/tslint/lib/language/rule/abstractRule.js:39:9)
    at Rule.apply (/Users/arimarkowitz/three-ts-types/node_modules/tslint/lib/rules/whitespaceRule.js:41:21)
    at Linter.applyRule (/Users/arimarkowitz/three-ts-types/node_modules/tslint/lib/linter.js:214:29)
    at /Users/arimarkowitz/three-ts-types/node_modules/tslint/lib/linter.js:155:85
    at Object.flatMap (/Users/arimarkowitz/three-ts-types/node_modules/tslint/lib/utils.js:160:29)
```

**Comment by Methuselah96** [comment]
Thanks for creating an issue, this has been happening for a while (it doesn't cause the command to fail). Would love it if someone could look into it.

**Comment by Methuselah96** [comment]
Looks like this a bug in `dtslint` (see https://github.com/microsoft/dtslint/issues/322) and presumably would need to be fixed in https://github.com/microsoft/DefinitelyTyped-tools since the original dtslint repo is archived.

**Comment by Methuselah96** [comment]
I think this no longer occurs (probably due to DT switching completely to eslint).
